#!/usr/bin/env python3
"""
job_search_daily.py — Autonomous Daily Job Search for Bo Osinupebi
===================================================================

PURPOSE
-------
Runs daily (via macOS launchd or cron) without any human interaction.
Each run:
  1. Fetches jobs from 7 sources in parallel (Canada + USA + Remote):
       - Job Bank Canada RSS     (Canadian gov't board, Toronto + all Canada)
       - Remotive API            (global remote, software-dev category)
       - We Work Remotely RSS    (full-stack + back-end remote feeds)
       - RemoteOK RSS            (broad global remote)
       - Himalayas API           (global remote, multiple queries)
       - Real Work From Anywhere (full-stack + backend remote RSS)
       - Jobicy RSS              (dev jobs, remote/hybrid/onsite)
  2. Deduplicates across all sources by URL
  3. Scores every job against Bo's Tier 1 keyword profile (remote = +0.5 bonus)
  4. Validates each candidate URL is live (HTTP HEAD — no dead links)
  5. Picks the top 5 highest-scoring jobs across all sources
  6. Skips jobs already seen in previous runs (deduplication via seen_jobs.json)
  7. Generates a tailored README, cover letter, and one-page resume for each job
  8. Converts all documents to PDF using md-to-pdf
  9. Organises output into:  claude jobs/YYYY-MM-DD/01-Company-Role/

REQUIREMENTS
------------
  - Python 3.8+
  - pip3 install -r requirements.txt --break-system-packages
  - claude CLI installed (used for text generation — no API key needed)
  - md-to-pdf installed: npm install -g md-to-pdf

USAGE
-----
  python3 job_search_daily.py              # normal daily run
  python3 job_search_daily.py --dry-run   # preview jobs found, no files written
  python3 job_search_daily.py --force     # ignore seen_jobs.json (re-process seen jobs)
  python3 job_search_daily.py --date 2026-03-22  # write into a specific date folder

OUTPUT STRUCTURE
----------------
  claude jobs/
    2026-03-22/
      01-CIBC-Full-Stack-NET/
        README.md
        cover-letter.md  cover-letter.pdf
        resume.md        resume.pdf
      02-.../
    logs/
      2026-03-22.log
    seen_jobs.json

SCHEDULING
----------
  See SETUP.md for launchd (macOS) and cron setup instructions.

AUTHOR
------
  Generated by Claude Code. See SETUP.md for maintenance notes.
"""

import argparse
import html
import json
import logging
import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from urllib.parse import quote_plus

import feedparser
import requests


# ─── PATHS ────────────────────────────────────────────────────────────────────

BASE_DIR = Path(__file__).parent.resolve()
CONFIG_FILE = BASE_DIR / "config.json"
SEEN_JOBS_FILE = BASE_DIR / "seen_jobs.json"
LOGS_DIR = BASE_DIR / "logs"
ENV_FILE = BASE_DIR / ".env"


# ─── PDF FRONT MATTER (shared by cover letter and resume) ─────────────────────

PDF_FRONT_MATTER = """\
---
pdf_options:
  format: Letter
  margin: 12mm 15mm
  printBackground: false
css: |
  body { font-family: Arial, sans-serif; font-size: 10.5pt; line-height: 1.35; }
  h1 { font-size: 16pt; margin: 0 0 2px 0; }
  h2 { font-size: 11pt; margin: 8px 0 3px 0; border-bottom: 1px solid #333; padding-bottom: 1px; }
  h3 { font-size: 10.5pt; margin: 6px 0 1px 0; }
  p { margin: 1px 0; }
  ul { margin: 2px 0; padding-left: 16px; }
  li { margin-bottom: 1px; }
  hr { margin: 4px 0; }
---

"""


# ─── JOB NORMALISATION ────────────────────────────────────────────────────────
# All source-specific fetchers return a list of dicts in this common shape.
# is_remote=True gets a scoring bonus but is never a hard requirement.

def make_job(
    title: str,
    company: str,
    location: str,
    description: str,
    url: str,
    source: str,
    is_remote: bool = False,
    published: str = "",
    query: str = "",
) -> dict:
    """Normalise a job into the standard dict used throughout the pipeline."""
    return {
        "title": title.strip(),
        "company": company.strip() or "Unknown Company",
        "location": location.strip() or "Unknown",
        "description": description[:3000],
        "url": url.strip(),
        "source": source,
        "is_remote": is_remote,
        "published": published,
        "query": query,
    }


def _clean_html(raw: str) -> str:
    """Strip HTML tags and collapse whitespace."""
    text = re.sub(r"<[^>]+>", " ", raw)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


# ─── SOURCE 1: JOB BANK CANADA RSS ───────────────────────────────────────────
# Canada's official government job board. Free Atom feed, no auth required.
# URL: https://www.jobbank.gc.ca/jobsearch/feed/jobSearchRSSfeed
# Covers all of Canada; summary HTML contains employer/location/salary fields.

def _parse_jobbank_summary(raw_html: str) -> tuple[str, str, str]:
    """Extract (company, location, salary) from Job Bank's structured HTML summary."""
    def field(label: str) -> str:
        m = re.search(
            rf"<strong>{re.escape(label)}:</strong>\s*(.*?)(?:<br|$)",
            raw_html, re.IGNORECASE | re.DOTALL,
        )
        return re.sub(r"<[^>]+>", "", m.group(1)).strip() if m else ""

    return (
        field("Employer") or "Unknown Company",
        field("Location") or "Canada",
        field("Salary") or "",
    )


def fetch_jobbank(config: dict, logger: logging.Logger) -> list[dict]:
    """
    Fetch jobs from Job Bank Canada RSS for each configured query.
    Runs queries in parallel. Not all jobs are remote — is_remote=False by default.
    """
    location = config["search"]["canada_location"]
    queries   = config["sources"]["jobbank"]["queries"]
    source    = "Job Bank Canada"
    results: list[dict] = []

    # Parse city and province from canada_location (e.g. "Toronto, ON" → "toronto", "on")
    _loc_parts = [p.strip().lower() for p in location.split(",")]
    _allowed_city     = _loc_parts[0] if _loc_parts else ""
    _allowed_province = _loc_parts[1] if len(_loc_parts) > 1 else ""

    def _fetch_one(query: str) -> list[dict]:
        url = (
            f"https://www.jobbank.gc.ca/jobsearch/feed/jobSearchRSSfeed"
            f"?searchstring={quote_plus(query)}"
            f"&locationstring={quote_plus(location)}"
        )
        try:
            feed = feedparser.parse(url)
            jobs = []
            skipped = 0
            for e in feed.entries:
                raw = getattr(e, "summary", "") or ""
                company, loc, salary = _parse_jobbank_summary(raw)
                desc = _clean_html(raw)
                if salary:
                    desc = f"Salary: {salary}. {desc}"
                # Job Bank's locationstring is not a strict filter — it returns all of Canada.
                # Enforce canada_location from config: keep only matching city/province, national, or remote.
                loc_lower = loc.lower()
                is_remote_loc = "remote" in loc_lower
                is_allowed_location = (
                    (_allowed_city     and _allowed_city     in loc_lower) or
                    (_allowed_province and _allowed_province in loc_lower)
                )
                is_national = loc_lower in ("canada", "") or loc_lower.startswith("canada,")
                if not (is_allowed_location or is_national or is_remote_loc):
                    skipped += 1
                    continue
                if link := getattr(e, "link", ""):
                    jobs.append(make_job(
                        title=getattr(e, "title", "Unknown").strip(),
                        company=company, location=loc, description=desc,
                        url=link, source=source, is_remote=is_remote_loc,
                        published=getattr(e, "published", ""), query=query,
                    ))
            if skipped:
                logger.info(f"  Job Bank '{query}': dropped {skipped} jobs outside '{location}'")
            logger.info(f"  Job Bank '{query}': {len(jobs)} entries")
            return jobs
        except Exception as exc:
            logger.warning(f"  Job Bank '{query}' failed: {exc}")
            return []

    with ThreadPoolExecutor(max_workers=len(queries)) as pool:
        for batch in pool.map(_fetch_one, queries):
            results.extend(batch)
    return results


# ─── SOURCE 2: REMOTIVE API ───────────────────────────────────────────────────
# Global remote jobs, JSON API. Software-dev category. No auth required.
# Rate limit: ~4 requests/day recommended — we make exactly 1 call.
# URL: https://remotive.com/api/remote-jobs?category=software-dev&limit=100

def fetch_remotive(config: dict, logger: logging.Logger) -> list[dict]:
    """Fetch remote software jobs from the Remotive JSON API."""
    cfg    = config["sources"]["remotive"]
    source = "Remotive"
    url    = f"https://remotive.com/api/remote-jobs?category=software-dev&limit={cfg['limit']}"
    try:
        resp = requests.get(url, timeout=15,
                            headers={"User-Agent": "Mozilla/5.0"})
        resp.raise_for_status()
        data = resp.json()
        jobs = []
        for j in data.get("jobs", []):
            desc = _clean_html(j.get("description", ""))
            salary = j.get("salary", "")
            if salary:
                desc = f"Salary: {salary}. {desc}"
            loc = j.get("candidate_required_location", "Remote") or "Remote"
            if link := j.get("url", ""):
                jobs.append(make_job(
                    title=j.get("title", ""),
                    company=j.get("company_name", ""),
                    location=loc, description=desc,
                    url=link, source=source, is_remote=True,
                    published=j.get("publication_date", ""),
                ))
        logger.info(f"  Remotive: {len(jobs)} entries")
        return jobs
    except Exception as exc:
        logger.warning(f"  Remotive failed: {exc}")
        return []


# ─── SOURCE 3: WE WORK REMOTELY RSS ──────────────────────────────────────────
# Curated remote jobs by category. Full-stack + back-end feeds. No auth.
# URLs: https://weworkremotely.com/categories/remote-{category}-jobs.rss

def fetch_weworkremotely(config: dict, logger: logging.Logger) -> list[dict]:
    """Fetch jobs from We Work Remotely RSS feeds (full-stack + back-end)."""
    feeds  = config["sources"]["weworkremotely"]["feeds"]
    source = "We Work Remotely"
    results: list[dict] = []

    def _fetch_one(feed_url: str) -> list[dict]:
        try:
            feed = feedparser.parse(feed_url)
            jobs = []
            for e in feed.entries:
                raw = getattr(e, "summary", "") or ""
                desc = _clean_html(raw)
                title = getattr(e, "title", "")
                # WWR titles are "Company: Role" — split if possible
                company = ""
                if ": " in title:
                    company, title = title.split(": ", 1)
                if link := getattr(e, "link", ""):
                    jobs.append(make_job(
                        title=title, company=company,
                        location="Remote", description=desc,
                        url=link, source=source, is_remote=True,
                        published=getattr(e, "published", ""),
                    ))
            logger.info(f"  WWR {feed_url.split('/')[-1]}: {len(jobs)} entries")
            return jobs
        except Exception as exc:
            logger.warning(f"  WWR {feed_url} failed: {exc}")
            return []

    with ThreadPoolExecutor(max_workers=len(feeds)) as pool:
        for batch in pool.map(_fetch_one, feeds):
            results.extend(batch)
    return results


# ─── SOURCE 4: REMOTEOK RSS ───────────────────────────────────────────────────
# Broad global remote job board. Standard RSS. No auth required.
# URL: https://remoteok.com/rss

def fetch_remoteok(config: dict, logger: logging.Logger) -> list[dict]:
    """Fetch jobs from RemoteOK RSS feed."""
    url    = config["sources"]["remoteok"]["url"]
    source = "RemoteOK"
    try:
        feed = feedparser.parse(url)
        jobs = []
        for e in feed.entries:
            raw  = getattr(e, "summary", "") or ""
            desc = _clean_html(raw)
            if link := getattr(e, "link", ""):
                jobs.append(make_job(
                    title=getattr(e, "title", ""),
                    company=getattr(e, "author", ""),
                    location="Remote", description=desc,
                    url=link, source=source, is_remote=True,
                    published=getattr(e, "published", ""),
                ))
        logger.info(f"  RemoteOK: {len(jobs)} entries")
        return jobs
    except Exception as exc:
        logger.warning(f"  RemoteOK failed: {exc}")
        return []


# ─── SOURCE 5: HIMALAYAS API ─────────────────────────────────────────────────
# Global remote jobs JSON API. Supports search queries. No auth required.
# URL: https://himalayas.app/jobs/api/search?query=...&limit=20

def fetch_himalayas(config: dict, logger: logging.Logger) -> list[dict]:
    """Fetch remote jobs from the Himalayas JSON API for each configured query."""
    cfg    = config["sources"]["himalayas"]
    source = "Himalayas"
    results: list[dict] = []

    def _fetch_one(query: str) -> list[dict]:
        url = (
            f"https://himalayas.app/jobs/api/search"
            f"?query={quote_plus(query)}&limit={cfg['limit']}"
        )
        try:
            resp = requests.get(url, timeout=15,
                                headers={"User-Agent": "Mozilla/5.0"})
            resp.raise_for_status()
            data = resp.json()
            jobs = []
            for j in data.get("jobs", []):
                desc = _clean_html(j.get("description", ""))
                loc  = j.get("location", "Remote") or "Remote"
                if link := j.get("url", j.get("applicationUrl", "")):
                    jobs.append(make_job(
                        title=j.get("title", ""),
                        company=j.get("company", {}).get("name", "") if isinstance(j.get("company"), dict) else j.get("company", ""),
                        location=loc, description=desc,
                        url=link, source=source, is_remote=True,
                        query=query,
                    ))
            logger.info(f"  Himalayas '{query}': {len(jobs)} entries")
            return jobs
        except Exception as exc:
            logger.warning(f"  Himalayas '{query}' failed: {exc}")
            return []

    with ThreadPoolExecutor(max_workers=len(cfg["queries"])) as pool:
        for batch in pool.map(_fetch_one, cfg["queries"]):
            results.extend(batch)
    return results


# ─── SOURCE 6: REAL WORK FROM ANYWHERE RSS ───────────────────────────────────
# Category-specific remote RSS feeds. Full-stack + backend. No auth required.

def fetch_realworkfromanywhere(config: dict, logger: logging.Logger) -> list[dict]:
    """Fetch jobs from Real Work From Anywhere RSS feeds."""
    feeds  = config["sources"]["realworkfromanywhere"]["feeds"]
    source = "Real Work From Anywhere"
    results: list[dict] = []

    def _fetch_one(feed_url: str) -> list[dict]:
        try:
            feed = feedparser.parse(feed_url)
            jobs = []
            for e in feed.entries:
                raw  = getattr(e, "summary", "") or ""
                desc = _clean_html(raw)
                if link := getattr(e, "link", ""):
                    jobs.append(make_job(
                        title=getattr(e, "title", ""),
                        company=getattr(e, "author", ""),
                        location="Remote", description=desc,
                        url=link, source=source, is_remote=True,
                        published=getattr(e, "published", ""),
                    ))
            logger.info(f"  RWFA {feed_url.split('/')[-2]}: {len(jobs)} entries")
            return jobs
        except Exception as exc:
            logger.warning(f"  RWFA {feed_url} failed: {exc}")
            return []

    with ThreadPoolExecutor(max_workers=len(feeds)) as pool:
        for batch in pool.map(_fetch_one, feeds):
            results.extend(batch)
    return results


# ─── SOURCE 7: JOBICY RSS ─────────────────────────────────────────────────────
# Dev jobs RSS feed. Includes remote, hybrid, and onsite roles. No auth.
# URL: https://jobicy.com/?feed=job_feed&job_categories=dev

def fetch_jobicy(config: dict, logger: logging.Logger) -> list[dict]:
    """Fetch developer jobs from Jobicy RSS feed."""
    url    = config["sources"]["jobicy"]["url"]
    source = "Jobicy"
    try:
        feed = feedparser.parse(url)
        jobs = []
        for e in feed.entries:
            raw  = getattr(e, "summary", "") or ""
            desc = _clean_html(raw)
            title = getattr(e, "title", "")
            # Detect remote from description/title
            is_remote = any(w in (title + desc).lower() for w in ["remote", "work from home", "wfh"])
            if link := getattr(e, "link", ""):
                jobs.append(make_job(
                    title=title,
                    company=getattr(e, "author", ""),
                    location="Remote" if is_remote else "USA/Global",
                    description=desc,
                    url=link, source=source, is_remote=is_remote,
                    published=getattr(e, "published", ""),
                ))
        logger.info(f"  Jobicy: {len(jobs)} entries")
        return jobs
    except Exception as exc:
        logger.warning(f"  Jobicy failed: {exc}")
        return []


# ─── AGGREGATE: FETCH ALL SOURCES ─────────────────────────────────────────────

def fetch_all_jobs(config: dict, logger: logging.Logger) -> list[dict]:
    """
    Fetch jobs from all 7 configured sources in parallel.
    Deduplicates by URL across all sources before returning.

    Sources:
      1. Job Bank Canada RSS  — Canadian gov't board
      2. Remotive API         — global remote, software-dev
      3. We Work Remotely RSS — curated remote full-stack + back-end
      4. RemoteOK RSS         — broad global remote
      5. Himalayas API        — global remote, multi-query
      6. Real Work From Anywhere RSS — category remote feeds
      7. Jobicy RSS           — dev jobs incl. remote/hybrid/onsite
    """
    fetchers = [
        fetch_jobbank,
        fetch_remotive,
        fetch_weworkremotely,
        fetch_remoteok,
        fetch_himalayas,
        fetch_realworkfromanywhere,
        fetch_jobicy,
    ]

    # Respect sources disabled via the UI (config key: "disabled_sources")
    disabled = set(config.get("disabled_sources", []))
    if disabled:
        fetchers = [f for f in fetchers if f.__name__.replace("fetch_", "") not in disabled]
        logger.info(f"Skipping disabled sources: {sorted(disabled)}")

    all_jobs: list[dict] = []
    seen_urls: set[str] = set()

    logger.info(f"Fetching from {len(fetchers)} sources in parallel...")
    with ThreadPoolExecutor(max_workers=len(fetchers)) as pool:
        futures = {pool.submit(f, config, logger): f.__name__ for f in fetchers}
        for future in as_completed(futures):
            source_name = futures[future]
            try:
                for job in future.result():
                    if job["url"] and job["url"] not in seen_urls:
                        seen_urls.add(job["url"])
                        all_jobs.append(job)
            except Exception as exc:
                logger.warning(f"  {source_name} raised: {exc}")

    logger.info(f"Total unique jobs fetched across all sources: {len(all_jobs)}")
    return all_jobs


# ─── FULL DESCRIPTION FETCHING ────────────────────────────────────────────────

# Job Bank Canada RSS entries only contain title/employer/salary.
# To score properly we need to fetch the full job posting page.
# We do this in a two-phase approach:
#   Phase 1: filter by title relevance (cheap, no HTTP requests)
#   Phase 2: fetch full description for title-qualified candidates only

TITLE_PASS_KEYWORDS = [
    "full stack", "fullstack", "full-stack",
    "software developer", "software engineer",
    "react", "node", "python", "backend", "front end", "frontend",
    "web developer", "application developer",
]


def title_qualifies(title: str) -> bool:
    """Quick check: does the job title suggest it's relevant to Bo's profile?"""
    t = title.lower()
    return any(kw in t for kw in TITLE_PASS_KEYWORDS)


def fetch_full_description(url: str, timeout: int = 10) -> str:
    """
    Fetch the full job description text from a Job Bank Canada posting page.

    Job Bank job pages have the description inside <div class="job-posting-detail">
    or similar. We extract all visible text from the main content section.

    Returns the description text (up to 3000 chars), or empty string on failure.
    """
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        )
    }
    try:
        resp = requests.get(url, headers=headers, timeout=timeout)
        if resp.status_code != 200:
            return ""
        html_text = resp.text

        # Extract text from the main job details section
        # Job Bank wraps the description in <article> or <div class="job-posting-detail">
        # Simple regex extraction — no BeautifulSoup dependency
        patterns = [
            r'<article[^>]*>(.*?)</article>',
            r'<div[^>]*class="[^"]*job-posting-detail[^"]*"[^>]*>(.*?)</div>',
            r'<div[^>]*id="[^"]*job-posting[^"]*"[^>]*>(.*?)</div>',
        ]
        for pattern in patterns:
            m = re.search(pattern, html_text, re.DOTALL | re.IGNORECASE)
            if m:
                raw = m.group(1)
                text = re.sub(r"<[^>]+>", " ", raw)
                text = html.unescape(text)
                text = re.sub(r"\s+", " ", text).strip()
                if len(text) > 100:
                    return text[:3000]

        # Fallback: extract all text from the page body
        body_m = re.search(r"<body[^>]*>(.*?)</body>", html_text, re.DOTALL | re.IGNORECASE)
        if body_m:
            text = re.sub(r"<[^>]+>", " ", body_m.group(1))
            text = html.unescape(text)
            text = re.sub(r"\s+", " ", text).strip()
            return text[:3000]

        return ""
    except Exception:
        return ""


# ─── SCORING ──────────────────────────────────────────────────────────────────

def score_job(job: dict, config: dict) -> tuple[int, float]:
    """
    Score a job against Bo's keyword profile using title + full description.

    Returns:
      (tier, score) where tier is 1, 2, or 3 and score is the float keyword count.

    Tier 1: 3+ Tier 1 keywords in text (case-insensitive)
    Tier 2: 2+ Tier 2 keywords (didn't qualify for Tier 1)
    Tier 3: everything else

    Bonus keywords add 0.5 each on top of the Tier 1 base score.

    NOTE: call fetch_full_description() first to populate job["description"]
    with the full posting text before scoring.
    """
    scoring = config["scoring"]
    text = (job["title"] + " " + job["description"]).lower()

    # Check exclude list — skip irrelevant roles
    excludes = config["search"].get("exclude_keywords", [])
    if any(ex.lower() in text for ex in excludes):
        return (3, 0.0)

    tier1_hits = sum(1 for kw in scoring["tier1_keywords"] if kw.lower() in text)
    bonus_hits = sum(0.5 for kw in scoring["tier1_bonus_keywords"] if kw.lower() in text)
    tier2_hits = sum(1 for kw in scoring["tier2_keywords"] if kw.lower() in text)

    # Remote is a preference, not a requirement — adds a small bonus
    remote_bonus = scoring.get("remote_bonus", 0.5) if job.get("is_remote") else 0.0

    if tier1_hits >= scoring["tier1_threshold"]:
        return (1, float(tier1_hits) + bonus_hits + remote_bonus)
    elif tier2_hits >= scoring["tier2_threshold"]:
        return (2, float(tier2_hits) + remote_bonus)
    else:
        return (3, remote_bonus)


# ─── AGE FILTER ───────────────────────────────────────────────────────────────

def is_recent(published: str, max_days: int) -> bool:
    """
    Return True if the published date string is within max_days of today,
    or if the date cannot be parsed (pass-through so we don't drop undated jobs).
    Handles RFC 2822 (feedparser) and ISO 8601 formats.
    """
    if not published:
        return True  # no date — don't discard
    from email.utils import parsedate_to_datetime
    now = datetime.now(tz=datetime.now().astimezone().tzinfo)
    for parser in (
        lambda s: parsedate_to_datetime(s),
        lambda s: datetime.fromisoformat(s.replace("Z", "+00:00")),
    ):
        try:
            pub_dt = parser(published)
            if pub_dt.tzinfo is None:
                pub_dt = pub_dt.replace(tzinfo=now.tzinfo)
            age_days = (now - pub_dt).days
            return age_days <= max_days
        except Exception:
            continue
    return True  # unparseable — pass through


# ─── URL VALIDATION ───────────────────────────────────────────────────────────

def validate_url(url: str, timeout: int = 5) -> tuple[bool, int]:
    """
    Check whether a job URL is still live.

    Uses HTTP HEAD (no body download) for efficiency.
    Falls back to GET if HEAD returns 405 Method Not Allowed.

    Returns:
      (is_live, status_code)
      is_live = True for 200, 301, 302; False for everything else
    """
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        )
    }
    try:
        resp = requests.head(url, headers=headers, timeout=timeout, allow_redirects=True)
        if resp.status_code == 405:
            # Server doesn't support HEAD — try GET
            resp = requests.get(url, headers=headers, timeout=timeout, allow_redirects=True, stream=True)
            resp.close()
        is_live = resp.status_code in (200, 301, 302)
        return is_live, resp.status_code
    except requests.exceptions.Timeout:
        return False, 0
    except requests.exceptions.ConnectionError:
        return False, 0
    except Exception:
        return False, 0


# ─── DEDUPLICATION ────────────────────────────────────────────────────────────

def load_seen_jobs() -> dict:
    """
    Load the seen_jobs.json file which tracks URLs already processed.
    Structure: { "url": "YYYY-MM-DD" }
    Returns empty dict if file doesn't exist yet.
    """
    if SEEN_JOBS_FILE.exists():
        try:
            with open(SEEN_JOBS_FILE) as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            return {}
    return {}


def save_seen_jobs(seen: dict) -> None:
    """Persist the seen_jobs dict back to disk."""
    with open(SEEN_JOBS_FILE, "w") as f:
        json.dump(seen, f, indent=2)


# ─── TEXT GENERATION ──────────────────────────────────────────────────────────

def find_claude_cli() -> str | None:
    """
    Locate the claude CLI binary.
    Checks PATH first, then the known nvm location.
    """
    # Try PATH
    found = shutil.which("claude")
    if found:
        return found
    # Known nvm location on this machine
    nvm_path = Path.home() / ".nvm/versions/node/v23.1.0/bin/claude"
    if nvm_path.exists():
        return str(nvm_path)
    return None


def generate_with_claude_cli(prompt: str, logger: logging.Logger) -> str | None:
    """
    Generate text using the locally installed claude CLI.

    Calls: claude -p "<prompt>" --output-format text
    This is non-interactive (print mode) — no API key required.
    Times out after 120 seconds.

    Returns the generated text, or None on failure.
    """
    claude_bin = find_claude_cli()
    if not claude_bin:
        logger.warning("claude CLI not found in PATH or known locations")
        return None

    try:
        result = subprocess.run(
            [claude_bin, "-p", prompt, "--output-format", "text"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
        else:
            logger.warning(f"claude CLI returned code {result.returncode}: {result.stderr[:200]}")
            return None
    except subprocess.TimeoutExpired:
        logger.warning("claude CLI timed out after 120s")
        return None
    except Exception as exc:
        logger.warning(f"claude CLI error: {exc}")
        return None


def generate_with_api(prompt: str, model: str, logger: logging.Logger) -> str | None:
    """
    Fallback text generation using the Anthropic API directly.
    Requires ANTHROPIC_API_KEY environment variable to be set.
    Only used if the claude CLI is unavailable.

    Returns the generated text, or None on failure.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        logger.warning("ANTHROPIC_API_KEY not set — API fallback unavailable")
        return None

    try:
        import anthropic  # noqa: PLC0415 — optional import

        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model=model,
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        return message.content[0].text.strip()
    except ImportError:
        logger.warning("anthropic package not installed — pip3 install anthropic")
        return None
    except Exception as exc:
        logger.warning(f"Anthropic API error: {exc}")
        return None


def generate_text(prompt: str, config: dict, logger: logging.Logger) -> str | None:
    """
    Try claude CLI first, fall back to Anthropic API, return None if both fail.
    Caller handles the None case gracefully (README-only mode).
    """
    text = generate_with_claude_cli(prompt, logger)
    if text:
        logger.debug("Text generated via claude CLI")
        return text

    logger.info("claude CLI unavailable — trying Anthropic API fallback")
    model = config["tools"]["claude_model_fallback"]
    text = generate_with_api(prompt, model, logger)
    if text:
        logger.debug("Text generated via Anthropic API")
        return text

    return None


# ─── PROMPT BUILDERS ──────────────────────────────────────────────────────────

def build_profile_block(config: dict) -> str:
    """Render Bo's full profile as a text block for use in prompts."""
    c = config["candidate"]
    exp_text = ""
    for role in c["experience"]:
        exp_text += f"\n  {role['title']} at {role['company']} ({role['dates']}, {role['location']})\n"
        for b in role["bullets"]:
            exp_text += f"    - {b}\n"

    edu_text = "\n".join(
        f"  {e['degree']} — {e['school']} ({e['dates']})" for e in c["education"]
    )

    return f"""
CANDIDATE PROFILE
Name: {c['name']}
Title: {c['title']}
Location: {c['location']}
Email: {c['email']}
Phone: {c['phone']}

Summary: {c['summary']}

Skills: {', '.join(c['skills'])}

Work Experience:{exp_text}
Education:
{edu_text}
""".strip()


def build_cover_letter_prompt(job: dict, config: dict) -> str:
    """
    Build the prompt used to generate a tailored cover letter.
    The output should be plain markdown (no code fences), ready to save directly.
    """
    profile = build_profile_block(config)
    c = config["candidate"]
    return f"""
You are writing a tailored cover letter for {c['name']}, a Full-Stack Software Developer in Toronto.

JOB DETAILS
-----------
Title: {job['title']}
Company: {job['company']}
Location: {job['location']}
Description: {job['description']}

CANDIDATE PROFILE
-----------------
{profile}

INSTRUCTIONS
------------
Write a professional, specific cover letter in plain markdown. Structure:
1. Header: Name, email, phone, date, "Hiring Manager, [Company]"
2. Opening paragraph: Name the exact role and team. Lead with the most relevant project from the candidate's background.
3. Body (2-3 paragraphs): Reference specific projects and metrics from the resume. Include 3 bolded bullet points with measurable achievements directly mapped to the job requirements.
4. Closing: Express genuine interest in the company's specific work. One sentence.
5. Sign-off: "Sincerely, {c['name']}"

Rules:
- Do NOT use generic phrases like "I am excited to apply" or "I believe I am a strong candidate"
- Reference actual project names and metrics (100,000+ requests, 99% uptime, $250K revenue, etc.)
- Keep it to one page when rendered — be concise
- Output only the markdown text, no code fences, no preamble
""".strip()


def build_resume_prompt(job: dict, config: dict) -> str:
    """
    Build the prompt used to generate a tailored one-page resume.
    The output must include the PDF front matter block verbatim, then the resume content.
    """
    profile = build_profile_block(config)
    c = config["candidate"]
    return f"""
You are writing a tailored one-page resume for {c['name']}, a Full-Stack Software Developer in Toronto.

JOB DETAILS
-----------
Title: {job['title']}
Company: {job['company']}
Description: {job['description']}

CANDIDATE PROFILE
-----------------
{profile}

INSTRUCTIONS
------------
Write a one-page resume in markdown. Start with EXACTLY this front matter block (copy it verbatim):

{PDF_FRONT_MATTER}

Then the resume content in this order:
1. Name (H1) + title line + contact on one line
2. ## Summary: 2-3 sentences. Lead with the job's core stack requirements. Be specific to this job.
3. ## Skills: Compress to 3 lines. Put the most relevant skills for THIS job first.
4. ## Experience: 3 roles. Limit to 5-6 bullets max per role. Bold all metrics.
5. ## Education: 2 lines only.

Rules:
- The whole thing MUST fit on one page (tight margins, small font via the CSS)
- Reorder skills and rewrite the summary to front-match this job's keywords
- Bold all numbers/metrics: **100,000+**, **99% uptime**, **$250K**, **90%**, **40%**, **50%**, **70%**
- Output ONLY the markdown (starting with ---), no preamble, no code fences
""".strip()


# ─── FOLDER & FILE CREATION ───────────────────────────────────────────────────

def slugify(text: str, max_len: int = 40) -> str:
    """Convert a string to a filesystem-safe slug."""
    text = re.sub(r"[^\w\s-]", "", text.lower())
    text = re.sub(r"[\s_-]+", "-", text).strip("-")
    return text[:max_len]


def create_job_folder(run_dir: Path, idx: int, job: dict) -> Path:
    """
    Create the numbered job subfolder inside the day's run directory.
    Example: claude jobs/2026-03-22/01-CIBC-Full-Stack-NET/
    """
    company_slug = slugify(job["company"])
    title_slug = slugify(job["title"])
    folder_name = f"{idx:02d}-{company_slug}-{title_slug}"
    folder = run_dir / folder_name
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def write_readme(folder: Path, job: dict, tier: int, score: float) -> None:
    """Write the README.md for a job application folder."""
    tier_label = {1: "1 — Strongest Match", 2: "2 — Strong Match", 3: "3 — Good Match"}[tier]
    remote_tag = " 🌐 Remote" if job.get("is_remote") else ""
    content = f"""# {job['title']} — {job['company']}

**Company:** {job['company']}
**Location:** {job['location']}{remote_tag}
**Tier:** {tier_label}
**Score:** {score:.1f}
**Source:** {job.get('source', 'Unknown')}
**Date found:** {datetime.now().strftime('%Y-%m-%d')}

## Job Link
{job['url']}

## Why You're a Strong Fit
*(Auto-generated — review and customise before applying)*

## Status
- [ ] Applied
- [ ] Phone screen
- [ ] Interview
- [ ] Offer

---
*Generated by job_search_daily.py — {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""
    (folder / "README.md").write_text(content, encoding="utf-8")


def write_cover_letter(folder: Path, content: str) -> Path:
    """Write cover-letter.md, prepending the PDF front matter."""
    # If the generated content already has front matter, don't add it again
    if content.strip().startswith("---"):
        full_content = content
    else:
        full_content = PDF_FRONT_MATTER + content
    path = folder / "cover-letter.md"
    path.write_text(full_content, encoding="utf-8")
    return path


def write_resume(folder: Path, content: str) -> Path:
    """Write resume.md — content should already include front matter from the prompt."""
    path = folder / "resume.md"
    path.write_text(content, encoding="utf-8")
    return path


def generate_pdf(md_file: Path, logger: logging.Logger) -> bool:
    """
    Convert a markdown file to PDF using md-to-pdf.
    The PDF is written alongside the .md file with the same base name.
    Returns True on success.
    """
    # Find md-to-pdf — check PATH and known nvm location
    md_to_pdf = shutil.which("md-to-pdf")
    if not md_to_pdf:
        nvm_bin = Path.home() / ".nvm/versions/node/v23.1.0/bin/md-to-pdf"
        if nvm_bin.exists():
            md_to_pdf = str(nvm_bin)

    if not md_to_pdf:
        logger.error("md-to-pdf not found — install with: npm install -g md-to-pdf")
        return False

    try:
        result = subprocess.run(
            [md_to_pdf, str(md_file)],
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode == 0:
            logger.debug(f"PDF generated: {md_file.with_suffix('.pdf').name}")
            return True
        else:
            logger.warning(f"md-to-pdf failed for {md_file.name}: {result.stderr[:200]}")
            return False
    except subprocess.TimeoutExpired:
        logger.warning(f"md-to-pdf timed out for {md_file.name}")
        return False
    except Exception as exc:
        logger.warning(f"md-to-pdf error: {exc}")
        return False


# ─── JOB PROCESSING ───────────────────────────────────────────────────────────

def process_job(
    run_dir: Path,
    idx: int,
    job: dict,
    tier: int,
    score: float,
    config: dict,
    logger: logging.Logger,
    dry_run: bool,
) -> dict:
    """
    Full pipeline for one job:
      1. Create folder
      2. Write README
      3. Generate cover letter via claude CLI (or fallback)
      4. Generate resume via claude CLI (or fallback)
      5. Convert both to PDF

    Returns a summary dict for logging.
    """
    summary = {
        "title": job["title"],
        "company": job["company"],
        "tier": tier,
        "score": score,
        "url": job["url"],
        "readme": False,
        "cover_letter": False,
        "resume": False,
        "pdf_cover": False,
        "pdf_resume": False,
    }

    if dry_run:
        logger.info(f"[DRY RUN] Would create: {slugify(job['company'])}-{slugify(job['title'])}")
        return summary

    folder = create_job_folder(run_dir, idx, job)
    logger.info(f"Created folder: {folder.name}")

    # README — always written
    write_readme(folder, job, tier, score)
    summary["readme"] = True
    logger.info(f"  ✓ README.md")

    # Cover letter
    cl_prompt = build_cover_letter_prompt(job, config)
    cl_text = generate_text(cl_prompt, config, logger)
    if cl_text:
        cl_path = write_cover_letter(folder, cl_text)
        summary["cover_letter"] = True
        logger.info(f"  ✓ cover-letter.md")
        if generate_pdf(cl_path, logger):
            summary["pdf_cover"] = True
            logger.info(f"  ✓ cover-letter.pdf")
    else:
        logger.warning(f"  ✗ cover letter generation failed — README only for this job")

    # Resume
    res_prompt = build_resume_prompt(job, config)
    res_text = generate_text(res_prompt, config, logger)
    if res_text:
        res_path = write_resume(folder, res_text)
        summary["resume"] = True
        logger.info(f"  ✓ resume.md")
        if generate_pdf(res_path, logger):
            summary["pdf_resume"] = True
            logger.info(f"  ✓ resume.pdf")
    else:
        logger.warning(f"  ✗ resume generation failed — README only for this job")

    return summary


# ─── LOGGING SETUP ────────────────────────────────────────────────────────────

def setup_logging(run_date: str) -> logging.Logger:
    """
    Configure logging to both a daily log file and stdout.
    Log file: claude jobs/logs/YYYY-MM-DD.log
    """
    LOGS_DIR.mkdir(exist_ok=True)
    log_file = LOGS_DIR / f"{run_date}.log"

    logger = logging.getLogger("job_search")
    logger.setLevel(logging.DEBUG)

    # File handler — DEBUG and above
    fh = logging.FileHandler(log_file, encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))

    # Console handler — INFO and above
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.INFO)
    ch.setFormatter(logging.Formatter("[%(levelname)s] %(message)s"))

    logger.addHandler(fh)
    logger.addHandler(ch)
    return logger


# ─── ENV LOADING ──────────────────────────────────────────────────────────────

def load_env() -> None:
    """
    Load variables from .env file into os.environ if .env exists.
    This is a lightweight manual loader — no python-dotenv dependency needed.
    """
    if not ENV_FILE.exists():
        return
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip())


# ─── CLEANUP ──────────────────────────────────────────────────────────────────

def cleanup_old_folders(
    base_dir: Path,
    keep: int,
    trigger_after: int,
    logger: logging.Logger,
    dry_run: bool,
) -> None:
    """
    Delete dated job folders (YYYY-MM-DD) beyond the most recent `keep` days.

    Retention policy (configured via config.json cleanup section):
      - Does nothing until `trigger_after` folders have accumulated (default 7)
      - Once triggered, keeps the newest `keep` folders (default 2), deletes the rest
      - Runs at the end of every daily script execution
      - Does NOT touch logs/, seen_jobs.json, config.json, or any script files

    Example with keep=2, trigger_after=7 on day 7:
      KEEP    → 2026-03-21, 2026-03-22
      DELETE  → 2026-03-16, 2026-03-17, 2026-03-18, 2026-03-19, 2026-03-20

    Days 1-6: no deletions — folders accumulate untouched.
    """
    date_pattern = re.compile(r"^\d{4}-\d{2}-\d{2}$")
    dated_dirs = sorted(
        [d for d in base_dir.iterdir() if d.is_dir() and date_pattern.match(d.name)],
        key=lambda d: d.name,  # lexicographic sort works for YYYY-MM-DD
    )

    if len(dated_dirs) < trigger_after:
        logger.info(
            f"Cleanup: {len(dated_dirs)} dated folder(s) — "
            f"waiting until {trigger_after} before trimming"
        )
        return

    to_delete = dated_dirs[:-keep] if len(dated_dirs) > keep else []

    if not to_delete:
        logger.info(f"Cleanup: {len(dated_dirs)} dated folders present — nothing to delete (keep={keep})")
        return

    logger.info(f"Cleanup: {len(dated_dirs)} dated folders found — keeping newest {keep}, deleting {len(to_delete)}")
    for folder in to_delete:
        if dry_run:
            logger.info(f"  [DRY RUN] Would delete: {folder.name}")
        else:
            try:
                import shutil as _shutil
                _shutil.rmtree(folder)
                logger.info(f"  Deleted: {folder.name}")
            except Exception as exc:
                logger.warning(f"  Failed to delete {folder.name}: {exc}")


# ─── MAIN ─────────────────────────────────────────────────────────────────────

def main() -> int:
    """
    Entry point. Returns exit code (0 = success, 1 = partial failure, 2 = total failure).
    """
    parser = argparse.ArgumentParser(
        description="Autonomous daily job search for Bo Osinupebi",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Preview jobs found and scored — create no files"
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Ignore seen_jobs.json — re-process previously seen jobs"
    )
    parser.add_argument(
        "--date", default=None, metavar="YYYY-MM-DD",
        help="Override the run date used for the output folder name"
    )
    args = parser.parse_args()

    # Determine run date
    run_date = args.date or datetime.now().strftime("%Y-%m-%d")

    # Setup
    load_env()
    logger = setup_logging(run_date)
    logger.info(f"=== Job search run: {run_date} {'[DRY RUN]' if args.dry_run else ''} ===")

    # Load config
    if not CONFIG_FILE.exists():
        logger.error(f"config.json not found at {CONFIG_FILE}")
        return 2
    with open(CONFIG_FILE) as f:
        config = json.load(f)

    # Load seen jobs (for dedup)
    seen_jobs: dict = {} if args.force else load_seen_jobs()
    if args.force:
        logger.info("--force: ignoring seen_jobs.json")
    else:
        logger.info(f"Loaded {len(seen_jobs)} previously seen job URLs")

    # ── Step 1: Fetch jobs ────────────────────────────────────────────────────
    all_jobs = fetch_all_jobs(config, logger)
    if not all_jobs:
        logger.warning("No jobs fetched — check RSS connectivity or try again later")
        return 1

    # ── Step 1b: Age filter ───────────────────────────────────────────────────
    max_age = config["search"].get("max_job_age_days", 3)
    recent_jobs = [j for j in all_jobs if is_recent(j.get("published", ""), max_age)]
    dropped = len(all_jobs) - len(recent_jobs)
    if dropped:
        logger.info(f"Age filter: dropped {dropped} jobs older than {max_age} days "
                    f"({len(recent_jobs)} remaining)")

    # ── Step 2: Phase 1 title filter — no HTTP requests ──────────────────────
    title_qualified = [j for j in recent_jobs if title_qualifies(j["title"])]
    logger.info(f"Title-qualified jobs (phase 1): {len(title_qualified)} / {len(all_jobs)}")

    # ── Step 2: Phase 2 — fetch full descriptions for title-qualified jobs ────
    # We do this in parallel to keep runtime reasonable (10 concurrent requests)
    logger.info(f"Fetching full descriptions for {len(title_qualified)} jobs...")
    with ThreadPoolExecutor(max_workers=10) as pool:
        futures = {pool.submit(fetch_full_description, j["url"]): j for j in title_qualified}
        for future in as_completed(futures):
            job = futures[future]
            full_desc = future.result()
            if full_desc:
                # Append full description to the short RSS summary
                job["description"] = (job["description"] + " " + full_desc)[:3000]

    # ── Step 2: Score and rank ────────────────────────────────────────────────
    scored: list[tuple[dict, int, float]] = []
    for job in title_qualified:
        tier, score = score_job(job, config)
        scored.append((job, tier, score))

    # Sort: Tier 1 first, then by score descending
    scored.sort(key=lambda x: (x[1], -x[2]))

    tier1 = [(j, t, s) for j, t, s in scored if t == 1]
    tier2 = [(j, t, s) for j, t, s in scored if t == 2]
    logger.info(f"Scored: {len(tier1)} Tier 1, {len(tier2)} Tier 2, "
                f"{len(scored) - len(tier1) - len(tier2)} Tier 3")

    max_results = config["search"]["max_results_per_tier"]
    candidates = tier1[:max_results]
    if len(candidates) < max_results:
        # Fill remaining slots with Tier 2 jobs
        shortfall = max_results - len(candidates)
        candidates += tier2[:shortfall]
        logger.info(f"Added {min(shortfall, len(tier2))} Tier 2 jobs to fill slots")

    if not candidates:
        logger.warning("No Tier 1 or Tier 2 jobs found today")
        return 1

    # ── Step 3: Dedup filter ──────────────────────────────────────────────────
    new_candidates = [
        (j, t, s) for j, t, s in candidates
        if j["url"] not in seen_jobs
    ]
    skipped_dedup = len(candidates) - len(new_candidates)
    if skipped_dedup:
        logger.info(f"Skipped {skipped_dedup} jobs already seen in previous runs")
    if not new_candidates:
        logger.info("All top jobs already seen — nothing new today")
        return 0

    # ── Step 4: URL validation ────────────────────────────────────────────────
    logger.info(f"Validating {len(new_candidates)} job URLs...")
    valid_candidates = []
    for job, tier, score in new_candidates:
        is_live, status_code = validate_url(job["url"])
        if is_live:
            logger.info(f"  LIVE ({status_code}): {job['title']} @ {job['company']}")
            valid_candidates.append((job, tier, score))
        else:
            logger.warning(f"  DEAD ({status_code}): {job['title']} @ {job['company']} — {job['url']}")

    if not valid_candidates:
        logger.warning("All candidate job URLs are dead — nothing to process")
        return 1

    # ── Step 5: Create run directory ──────────────────────────────────────────
    run_dir = BASE_DIR / run_date
    if not args.dry_run:
        run_dir.mkdir(exist_ok=True)
        logger.info(f"Output directory: {run_dir}")

    # ── Step 6: Process each job ──────────────────────────────────────────────
    summaries = []
    new_seen = {}

    for idx, (job, tier, score) in enumerate(valid_candidates, start=1):
        logger.info(f"\n[{idx}/{len(valid_candidates)}] {job['title']} @ {job['company']} "
                    f"(Tier {tier}, score {score:.1f})")
        summary = process_job(run_dir, idx, job, tier, score, config, logger, args.dry_run)
        summaries.append(summary)
        if not args.dry_run:
            new_seen[job["url"]] = run_date

    # ── Step 7: Save seen jobs ────────────────────────────────────────────────
    if not args.dry_run and new_seen:
        seen_jobs.update(new_seen)
        save_seen_jobs(seen_jobs)
        logger.info(f"\nSaved {len(new_seen)} new job URLs to seen_jobs.json")

    # ── Step 8: Summary ───────────────────────────────────────────────────────
    logger.info("\n=== Run Summary ===")
    success_count = 0
    for s in summaries:
        status = "✓" if s["readme"] else "✗"
        cl_status = "✓" if s["pdf_cover"] else ("md" if s["cover_letter"] else "✗")
        res_status = "✓" if s["pdf_resume"] else ("md" if s["resume"] else "✗")
        logger.info(
            f"  {status} {s['company']} — {s['title']} "
            f"| cover={cl_status} resume={res_status} | Tier {s['tier']}"
        )
        if s["readme"]:
            success_count += 1

    logger.info(f"\nProcessed {success_count}/{len(valid_candidates)} jobs successfully")
    logger.info(f"Output: {run_dir}" if not args.dry_run else "Dry run — no files written")

    # ── Step 9: Clean up old dated folders ───────────────────────────────────
    cleanup_cfg = config.get("cleanup", {})
    cleanup_old_folders(
        BASE_DIR,
        keep=cleanup_cfg.get("keep_days", 2),
        trigger_after=cleanup_cfg.get("trigger_after_days", 7),
        logger=logger,
        dry_run=args.dry_run,
    )

    logger.info("=== Done ===\n")

    if args.dry_run:
        return 0  # dry-run exits 0 whenever jobs were found and previewed
    return 0 if success_count == len(valid_candidates) else 1


if __name__ == "__main__":
    sys.exit(main())
